### ISSUE TITLE
A SHOT IN THE DARK

### ISSUE THREAD

**Issue by isaiahwash3r3** [Justintime50/Justintime50#2]
I've been studying coding for a little minute now and I know it's a shot in the dark but I would like for you to be my mentor. I know you probably get asked this often but I am really eager to learn and already have been studying on my own right now just JavaScript but I'm eager to learn whatever. So if it doesn't take up to much of your time could you PLEASE CONSIDER IT p.s. how bad would it be to have a protege

**Comment by Justintime50** [comment]
Find me on LinkedIn and we can continue the conversation there. GitHub (specifically on repositories) isn't a place for these kinds of discussions.
